// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module('App.File', function(exports, top) {
    var Collection, Model, UIState, Views, _ref;
    Model = (function(_super) {

      __extends(Model, _super);

      function Model() {
        return Model.__super__.constructor.apply(this, arguments);
      }

      Model.prototype.syncName = 'file';

      Model.prototype.idAttribute = '_id';

      Model.prototype.thumbBase = "http://s3.amazonaws.com/lingualabio-media";

      Model.prototype.iconHash = {
        video: 'facetime-video',
        image: 'picture',
        pdf: 'file',
        audio: 'volume-up'
      };

      Model.prototype.src = function() {
        switch (this.get('type')) {
          case 'image':
            return this.get('imageUrl');
          case 'video':
            if (top.Modernizr.video.webm) {
              return this.get('webmUrl');
            } else if (top.Modernizr.video.h264) {
              return this.get('h264Url');
            }
            break;
          case 'audio':
            return this.get('mp3Url');
        }
      };

      Model.prototype.thumbnail = function() {
        var _ref, _ref1;
        return (_ref = (_ref1 = this.get('thumbUrl')) != null ? _ref1 : this.get('imageUrl')) != null ? _ref : 'http://placehold.it/100x100';
      };

      Model.prototype.icon = function() {
        if (this.get('type') === 'application') {
          return this.iconHash[this.get('ext')];
        } else {
          return this.iconHash[this.get('type')];
        }
      };

      Model.prototype.match = function(query) {
        var re;
        re = new RegExp(query, 'i');
        return true;
      };

      Model.prototype.modelType = function(plural) {
        if (plural == null) {
          plural = false;
        }
        return "file" + (plural ? 's' : '');
      };

      Model.prototype.displayTitle = function() {
        return "" + (this.get('title')) + ")";
      };

      Model.prototype.isSelected = function() {
        return this.get('selected');
      };

      Model.prototype.toggleSelect = function() {
        return this.set('selected', !this.get('selected'));
      };

      return Model;

    })(Backbone.Model);
    Collection = (function(_super) {

      __extends(Collection, _super);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.model = Model;

      Collection.prototype.syncName = 'file';

      Collection.prototype.comparator = function() {
        return 0 - moment(this.get('modified')).valueOf();
      };

      Collection.prototype.filteredBy = function(searchTerm) {
        return this.filter(function(m) {
          var re;
          re = new RegExp(searchTerm, 'i');
          return re.test(m.get('title'));
        });
      };

      Collection.prototype.fromDB = function(data) {
        var method, model, options;
        method = data.method, model = data.model, options = data.options;
        console.log('updating ', model);
        switch (method) {
          case 'create':
            return this.add(model);
          case 'update':
            return this.get(model._id).set(model);
          case 'progress':
            console.log('setting: ', model);
            return this.get(model._id).set(model);
          case 'status':
            return this.get(model._id).set(model);
        }
      };

      Collection.prototype.modelType = function() {
        return "files";
      };

      Collection.prototype.initialize = function() {
        var _this = this;
        return this.on('reset', function() {
          var id, _i, _len, _ref, _results;
          if (_this._selected) {
            _ref = _this._selected;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              id = _ref[_i];
              _results.push(_this.get(id).toggleSelect());
            }
            return _results;
          }
        });
      };

      Collection.prototype.selected = function() {
        return this.filter(function(s) {
          return s.isSelected();
        });
      };

      Collection.prototype.selectionState = function() {
        var selState;
        if (this.selectedFiltered().length === this.filtered().length) {
          selState = 'all';
        } else if (this.selectedFiltered().length === 0) {
          selState = 'none';
        } else {
          selState = 'some';
        }
        return selState;
      };

      Collection.prototype.filtered = function() {
        var _this = this;
        return this.filter(function(m) {
          var _ref;
          return m.match((_ref = _this.searchTerm) != null ? _ref : '');
        });
      };

      Collection.prototype.selectedFiltered = function() {
        return _.filter(this.filtered(), function(m) {
          return m.get('selected') === true;
        });
      };

      Collection.prototype.selectFiltered = function(setTo) {
        var student, _i, _len, _ref, _results;
        if (setTo == null) {
          setTo = true;
        }
        _ref = this.filtered();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          student = _ref[_i];
          _results.push(student.set('selected', setTo));
        }
        return _results;
      };

      Collection.prototype.toggleSelectFiltered = function() {
        if (this.selectedFiltered().length === this.filtered().length) {
          return this.selectFiltered(false);
        } else if (this.selectedFiltered().length === 0) {
          return this.selectFiltered(true);
        } else {
          return this.selectFiltered(false);
        }
      };

      return Collection;

    })(Backbone.Collection);
    UIState = (function(_super) {

      __extends(UIState, _super);

      function UIState() {
        return UIState.__super__.constructor.apply(this, arguments);
      }

      UIState.prototype.defaults = {
        searchTerm: '',
        currentListView: 'list',
        adding: false
      };

      return UIState;

    })(Backbone.Model);
    exports.Views = Views = {};
    Views.Main = (function(_super) {

      __extends(Main, _super);

      function Main() {
        return Main.__super__.constructor.apply(this, arguments);
      }

      Main.prototype.tagName = 'div';

      Main.prototype.className = 'files-main container';

      Main.prototype.selectIcons = {
        'all': 'check',
        'none': 'check-empty',
        'some': 'reorder'
      };

      Main.prototype.selectStrings = {
        'all': 'Unselect all',
        'none': 'Select all',
        'some': 'Unselect all'
      };

      Main.prototype.initialize = function() {
        var _this = this;
        this.state = new UIState;
        this.searchBox = new top.App.Teacher.Views.SearchBox;
        this.collection.on('reset', this.render, this);
        return this.collection.on('add', function(i) {
          return _this.addItem(i);
        });
      };

      Main.prototype.events = {
        'click .add-file': 'openFilePicker',
        'click .delete-students': function() {
          var dc;
          dc = new UI.ConfirmDelete({
            collection: this.collection
          });
          return dc.render().open();
        },
        'click .toggle-select-all': function() {
          return this.collection.toggleSelectFiltered();
        }
      };

      Main.prototype.controlsTemplate = function() {
        return div({
          "class": 'btn-toolbar span12'
        }, function() {
          div({
            "class": 'btn-group pull-left'
          }, function() {
            var selState;
            return button({
              "class": "btn btn-mini pull-left icon-" + this.selectIcons[selState = this.collection.selectionState()] + " toggle-select-all"
            }, " " + this.selectStrings[selState]);
          });
          div({
            "class": 'btn-group pull-right'
          }, function() {
            return button({
              rel: 'tooltip',
              'data-original-title': 'You can upload files from your computer or services like Dropbox and Google Drive',
              "class": "btn btn-mini btn-success icon-plus add-file"
            }, ' Add');
          });
          if (this.collection.selected().length) {
            div({
              "class": 'btn-group pull-left'
            }, function() {});
            return div({
              "class": 'btn-group pull-right'
            }, function() {
              return button({
                "class": 'btn btn-mini btn-danger icon-trash delete-students'
              }, ' Delete');
            });
          }
        });
      };

      Main.prototype.template = function() {
        div({
          "class": 'message-cont'
        }, function() {});
        div({
          "class": 'controls-cont row'
        }, function() {});
        return table({
          "class": 'list-cont table'
        }, function() {
          thead({
            "class": 'new-item-cont'
          });
          return tbody({
            "class": 'list'
          }, function() {});
        });
      };

      Main.prototype.addItem = function(file, prepend) {
        var v, _ref;
        if (prepend == null) {
          prepend = false;
        }
        if (this.collection.length === 1) {
          if ((_ref = this.msg) != null) {
            _ref.remove();
          }
        }
        v = new Views.ListItem({
          model: file,
          collection: this.collection
        });
        v.render();
        if (prepend) {
          v.$el.prependTo(this.$('.list'));
        } else {
          v.$el.appendTo(this.$('.list'));
        }
        return file.on('change:selected', this.renderControls, this);
      };

      Main.prototype.openFilePicker = function() {
        var _this = this;
        return window.filepicker.getFile('*/*', {
          modal: true,
          persist: false,
          location: filepicker.SERVICES.COMPUTER
        }, function(url, data) {
          console.log(url, data);
          return _this.collection.create(new Model({
            title: data.filename,
            filename: data.filename,
            size: data.size,
            type: data.type.split('/')[0],
            mime: data.type,
            fpUrl: url
          }));
        });
      };

      Main.prototype.handleFileUpload = function() {
        return console.log($('.file-picker-url').val());
      };

      Main.prototype.renderControls = function() {
        this.$('.controls-cont').html(ck.render(this.controlsTemplate, this));
        return this;
      };

      Main.prototype.renderList = function() {
        var stu, _i, _len, _ref, _ref1, _results;
        this.$('.list').empty();
        _ref1 = (_ref = this.collection.filtered()) != null ? _ref : this.collection.models;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          stu = _ref1[_i];
          _results.push(this.addItem(stu));
        }
        return _results;
      };

      Main.prototype.render = function() {
        this.$el.html(ck.render(this.template, this));
        if (!this.collection.length) {
          this.msg = new UI.Alert({
            message: 'You have no media files to use for your activities! Click the green Add button below to get started.'
          });
          this.msg.render().open(this.$('.message-cont'));
        }
        this.renderList();
        this.renderControls();
        this.$('button').tooltip({
          placement: 'bottom'
        });
        this.searchBox.setElement($('input#search-box')[0]);
        this.delegateEvents();
        return this;
      };

      return Main;

    })(Backbone.View);
    Views.ListItem = (function(_super) {

      __extends(ListItem, _super);

      function ListItem() {
        return ListItem.__super__.constructor.apply(this, arguments);
      }

      ListItem.prototype.tagName = 'tr';

      ListItem.prototype.className = 'list-item';

      ListItem.prototype.initialize = function() {
        var _this = this;
        this.model.on('change', function() {
          return _this.renderThumb();
        });
        this.model.on('change:selected', function() {
          return _this.render();
        });
        return this.model.on('remove', function() {
          return _this.remove();
        });
      };

      ListItem.prototype.events = {
        'change .title': function(e) {
          return this.model.save({
            title: $(e.target).val()
          });
        },
        'click .dl': 'downloadItem',
        'click .select-item': function() {
          return this.model.toggleSelect();
        },
        'click .delete-item': function() {
          var dc;
          dc = new UI.ConfirmDelete({
            model: this.model
          });
          return dc.render().open();
        }
      };

      ListItem.prototype.thumbTemplate = function() {
        if (this.get('status') !== 'finished') {
          div('processing');
          return div({
            "class": 'progress progress-striped active'
          }, function() {
            return div({
              "class": 'bar',
              style: "width: " + (this.get('prepProgress' || 5)) + "%"
            });
          });
        } else {
          if (this.thumbnail()) {
            return img({
              src: "" + (this.thumbnail()),
              "class": 'thumb'
            });
          } else {
            return i({
              "class": "icon-" + (this.icon()) + " icon-large"
            });
          }
        }
      };

      ListItem.prototype.template = function() {
        var urls;
        urls = this.get('urls');
        td(function() {
          return i({
            "class": "" + (this.isSelected() ? 'icon-check' : 'icon-check-empty') + " select-item"
          });
        });
        td({
          "class": 'thumb-cont'
        }, function() {});
        td(function() {
          return input({
            "class": 'title',
            value: "" + (this.get('title'))
          });
        });
        td(moment(this.get('created')).format("MMM D h:mm:ss a"));
        td({
          "class": 'tags-cont'
        }, function() {});
        return td(function() {
          return span({
            "class": 'btn-group'
          }, function() {
            button({
              rel: 'tooltip',
              "class": 'btn btn-mini download-item icon-share',
              'data-original-title': 'download to your computer or another storage service'
            });
            return button({
              rel: 'tooltip',
              "class": 'btn btn-mini delete-item icon-trash',
              'data-original-title': 'delete this file'
            });
          });
        });
      };

      ListItem.prototype.deleteItem = function() {
        return this.model.destroy();
      };

      ListItem.prototype.downloadItem = function() {
        var _this = this;
        return filepicker.saveAs(this.model.src(), this.model.get('mime'), function(url) {
          return _this.collection.create(new Model({
            title: data.filename,
            filename: data.filename,
            size: data.size,
            type: data.type.split('/')[0],
            mime: data.type,
            fpUrl: url
          }));
        });
      };

      ListItem.prototype.renderThumb = function() {
        return this.$('.thumb-cont').html(ck.render(this.thumbTemplate, this.model));
      };

      ListItem.prototype.render = function() {
        this.delegateEvents();
        ListItem.__super__.render.call(this);
        this.renderThumb();
        this.$('button').tooltip({
          placement: 'bottom'
        });
        return this;
      };

      return ListItem;

    })(Backbone.View);
    return _ref = [Model, Collection, UI], exports.Model = _ref[0], exports.Collection = _ref[1], exports.UI = _ref[2], _ref;
    /*
      class Views.Main extends Backbone.View
        tagName: 'div'
        className: 'files-main container'
    
        initialize: ->
          @listView = new Views.List { collection: @collection }
    
          @ui = new UIState()
    
          @collection.on 'reset', =>
            @renderList()
    
    
    
        events:
          'click .select-browser-view': -> @ui.set 'currentListView', 'browser'
          'click .select-list-view': -> @ui.set 'currentListView', 'list'
    
          'keyup .search-query': 'search'
          'click .record-upload': 'openRecorder'
          'click .file-picker': 'openFilePicker'
    
        search: (e)->
          clearTimeout @searchWait
          @searchWait = wait 200, => @ui.set 'searchTerm', $(e.target).val()
    
    
        template: ->
              
          div class:'row files-top-bar', ->
            span class:'btn-toolbar span4', ->
              div class:'input-prepend', ->
                span class:'add-on icon-search'
                input class:'search-query span3', type:'text', placeholder:'search'
            span class:'btn-toolbar span8 pull-right', ->
              button class:'btn btn-success icon-plus file-picker pull-right', ' Add a file'
    
            
          div class:'files-list-cont span10', ->
          div class:'file-detail-cont'
    
        openFilePicker: ->
          window.filepicker.getFile '', { modal: true, persist: false, location: filepicker.SERVICES.COMPUTER }, (url,data)=>
            console.log url, data
            @collection.create new Model { title: data.filename, filename: data.filename, size: data.size, type: data.type.split('/')[0], mime: data.type, fpUrl: url }
    
        handleFileUpload: ->
          console.log $('.file-picker-url').val()
    
        openRecorder: ->
          @recorder?.remove()
          @recorder ?= new Views.Recorder()
          @recorder.render().open()
          @
    
        renderList: ->
          @listView.render().open @$('.files-list-cont')
          @
    
        render: ->
          @$el.html ck.render @template, @
          @renderList()
    
          @$('.tt').tooltip()
    
               
          @delegateEvents()
          @
    
      class Views.Recorder extends Backbone.View
        tagName: 'div'
        className: 'modal popup-recorder'
    
        template: ->
          div class:'modal-header', ->
            h2 'Record and upload your voice'
          div class:'modal-body', ->
          div class:'modal-footer', ->
            button class:'btn', ->
              text ' Nevermind'
            button class:'btn btn-success', ->
              i class:'icon-upload'
              text ' Upload it!'
    
    
        render: ->
          super()
          @recorder ?= new App.Recording.Views.Recorder()
          @recorder.render().open @$('.modal-body')
          @$el.modal('show')
          @
    
    
      class Views.List extends Backbone.View
        tagName: 'table'
        className: 'table file-list'
    
        initialize: ->
          @collection.on 'add', @addItem
    
    
          @collection.on 'reset', => @render()
    
    
        doSearch: (@searchTerm)->
          @render()
    
        template: ->
          thead ->
          tbody ->
          tfoot ->
              
    
        addItem: (f)=>
          f.listItemView?.remove()
          f.listItemView ?= new Views.ListItem { model: f }
          f.listItemView.render().open @$('tbody')
          @
        
        render: ->
          @$el.html ck.render @template, @collection
          @addItem f for f in (if @searchTerm then @collection.filteredBy(@searchTerm) else @collection.models)
    
          upl = @collection.uploadFile
          input = @$('.select-upload').browseElement()
          input.on 'change', (e)->
            for f in e.target.files
              console.log 'uploading ',f
              upl f
    
          @delegateEvents()
          @
    
    
      class Views.ListItem extends Backbone.View
        tagName: 'tr'
        className: 'list-item'
    
        initialize: ->
          @model.on 'change', => @renderThumb()
          @model.on 'remove', => @remove()
    
        events:
          'change .title': (e)->
            @model.save({ title: $(e.target).val() })
          'click .delete': 'deleteItem'
          'click .dl': 'downloadItem'
          'dblclick': -> @model.collection.trigger 'selected', @model
    
    
        thumbTemplate: ->
          if @get('status') isnt 'finished'
            div 'processing'
            div class:'progress progress-striped active', ->
              div class:'bar', style:"width: #{@get 'prepProgress' or 5}%"
          else 
            if @thumbnail()
              img src:"#{@thumbnail()}", class:'thumb'
            else
              i class:"icon-#{@icon()} icon-large"
    
        template: ->
          urls = @get('urls')
          td class:'thumb-cont', -> 
            
          td -> input class:'title', value:"#{ @get('title') }"
          td moment(@get('created')).format("MMM D h:mm:ss a")
          td class:'tags-cont', -> 
          td -> i class:'icon-share-alt dl'
          td -> i class:'icon-trash delete'
    
    
        deleteItem: ->
          @model.destroy()
    
        downloadItem: ->
          filepicker.saveAs @model.src(), @model.get('mime'), (url)->
            console.log url
    
        renderThumb: ->
          @$('.thumb-cont').html ck.render @thumbTemplate, @model
    
        render: ->
          @delegateEvents()
          super()
          @renderThumb()
          @
    
    
      class Views.Detail extends Backbone.View
        tagName: 'div'
        className: 'file-video-detail'
    
        template: ->
          switch @get 'type'
            when 'video'
              video class:'video',src:"#{@src()}"
            when 'image'
              img src:"#{@src()}"
    */

  });

  module('App.Lab', function(exports, top) {
    var Collection, Model, Views, _ref;
    Model = (function(_super) {

      __extends(Model, _super);

      function Model() {
        return Model.__super__.constructor.apply(this, arguments);
      }

      Model.prototype.syncName = 'lab';

      Model.prototype.idAttribute = '_id';

      return Model;

    })(Backbone.Model);
    Collection = (function(_super) {

      __extends(Collection, _super);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.model = Model;

      Collection.prototype.syncName = 'lab';

      return Collection;

    })(Backbone.Collection);
    _ref = [Model, Collection], exports.Model = _ref[0], exports.Collection = _ref[1];
    exports.Views = Views = {};
    return Views.Main = (function(_super) {

      __extends(Main, _super);

      function Main() {
        return Main.__super__.constructor.apply(this, arguments);
      }

      Main.prototype.tagName = 'div';

      Main.prototype.className = 'lab-view container';

      Main.prototype.initialize = function() {};

      Main.prototype.template = function() {
        return div({
          "class": 'row-fluid'
        }, function() {
          div({
            "class": 'media-cont span6'
          }, function() {
            return p('media');
          });
          return div({
            "class": 'message-cont span6',
            'contenteditable': 'true'
          }, function() {
            return "" + (this.get('status').message);
          });
        });
      };

      return Main;

    })(Backbone.View);
  });

  module('App.Recording', function(exports, top) {
    var Collection, Model, Views;
    Model = (function(_super) {

      __extends(Model, _super);

      function Model() {
        return Model.__super__.constructor.apply(this, arguments);
      }

      return Model;

    })(App.File.Model);
    Collection = (function(_super) {

      __extends(Collection, _super);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.model = Model;

      return Collection;

    })(Backbone.Collection);
    exports.Views = Views = {};
    return Views.Recorder = (function(_super) {

      __extends(Recorder, _super);

      function Recorder() {
        return Recorder.__super__.constructor.apply(this, arguments);
      }

      Recorder.prototype.tagName = 'div';

      Recorder.prototype.className = 'recorder';

      Recorder.prototype.initialize = function() {};

      Recorder.prototype.events = {
        'click .record': 'record',
        'click .play': 'play',
        'click .stop': 'stop',
        'click .pause': 'pause'
      };

      Recorder.prototype.template = function() {
        applet({
          "class": 'recorder-applet',
          archive: '/java/nanogong.jar',
          code: 'gong.NanoGong',
          width: 150,
          height: 40
        }, function() {
          param({
            name: 'AudioFormat',
            value: 'Speex'
          });
          param({
            name: 'MaxDuration',
            value: '1200'
          });
          return param({
            name: 'SamplingRate',
            value: '16000'
          });
        });
        div({
          "class": 'scrubber'
        }, function() {});
        div({
          "class": 'status'
        });
        return div({
          "class": 'recorder-main'
        }, function() {
          button({
            "class": 'btn btn-danger record state-stopped state-closed state-paused-recording'
          }, function() {
            i({
              "class": 'icon-comment'
            });
            return text(' rec');
          });
          button({
            "class": 'btn pause state-playing state-recording'
          }, function() {
            i({
              "class": 'icon-pause'
            });
            return text(' pause');
          });
          button({
            "class": 'btn btn-success play state-paused state-stopped state-paused'
          }, function() {
            i({
              "class": 'icon-play'
            });
            return text(' play');
          });
          return button({
            "class": 'btn btn-inverse stop state-paused state-recording state-playing state-paused-recording'
          }, function() {
            i({
              "class": 'icon-stop'
            });
            return text(' stop');
          });
        });
      };

      Recorder.prototype.appEvents = function() {
        var _this = this;
        return doEvery(200, function() {
          return _this.statusCheck();
        });
      };

      Recorder.prototype.handleNewStatus = function() {
        this.$('.recorder-main .btn').hide();
        return this.$(".recorder-main .state-" + this.status).show();
      };

      Recorder.prototype.statusCheck = function() {
        if (this.status !== (this.status = this.getStatus().replace(' ', '-'))) {
          this.trigger('status', this.status);
          this.$('.status').text(this.status);
          return this.handleNewStatus();
        }
      };

      Recorder.prototype.render = function() {
        var _ref;
        Recorder.__super__.render.call(this);
        this.rec = this.$('.recorder-applet')[0];
        this.appEvents();
        if ((_ref = this.scrubber) == null) {
          this.scrubber = new UI.Slider();
        }
        this.scrubber.render().open(this.$('.scrubber'));
        return this;
      };

      Recorder.prototype._req = function() {
        var args, res, _ref;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        res = (_ref = this.rec).sendGongRequest.apply(_ref, args);
        return res;
      };

      Recorder.prototype.record = function() {
        var duration;
        duration = this._req('RecordMedia', 'audio', 1200000);
        return this;
      };

      Recorder.prototype.stop = function() {
        this._req('StopMedia', 'audio');
        return this;
      };

      Recorder.prototype.pause = function() {
        this._req('PauseMedia', 'audio');
        return this;
      };

      Recorder.prototype.clear = function() {
        this._req('ClearMedia', 'audio');
        return this;
      };

      Recorder.prototype.play = function() {
        this._req('PlayMedia', 'audio');
        return this;
      };

      Recorder.prototype.getStatus = function() {
        return this._req('GetMediaStatus', 'audio');
      };

      Recorder.prototype.getTime = function() {
        return this._req('GetMediaTime', 'audio');
      };

      Recorder.prototype.setTime = function(s) {
        this._req('SetMediaTime', 'audio', Math.floor(s * 1000));
        return this;
      };

      Recorder.prototype.getAudioLevel = function() {
        return this._req('GetAudioLevel', 'audio');
      };

      Recorder.prototype.upload = function() {
        return this._req('PostToForm', 'http://lingualab.io/upload', 'file', '', 'recording.spx');
      };

      return Recorder;

    })(Backbone.View);
  });

  module('App.Student', function(exports, top) {
    var Collection, Model, UIState, Views, _ref;
    exports.Views = Views = {};
    Model = (function(_super) {

      __extends(Model, _super);

      function Model() {
        return Model.__super__.constructor.apply(this, arguments);
      }

      Model.prototype.syncName = 'student';

      Model.prototype.idAttribute = '_id';

      Model.prototype.initialize = function() {};

      Model.prototype.getLoginKey = function(cb) {
        return this.sync('getLoginKey', this.toJSON(), {
          error: cb,
          success: cb
        });
      };

      Model.prototype.modelType = function(plural) {
        if (plural == null) {
          plural = false;
        }
        return "student" + (plural ? 's' : '');
      };

      Model.prototype.displayTitle = function() {
        return "" + (this.get('name')) + " (" + (this.get('email')) + ")";
      };

      Model.prototype.isSelected = function() {
        return this.get('selected');
      };

      Model.prototype.toggleSelect = function() {
        return this.set('selected', !this.get('selected'));
      };

      Model.prototype.randomPassword = function() {};

      Model.prototype.passwordMask = function() {
        var pw;
        pw = this.get('password');
        return pw.replace(/./g, '*');
      };

      Model.prototype.match = function(query) {
        var re;
        re = new RegExp(query, 'i');
        return (re.test(this.get('name'))) || (re.test(this.get('email')));
      };

      Model.prototype.changePennies = function(byAmount, cb) {
        var _this = this;
        return this.sync('changePennies', this.toJSON(), {
          byAmount: byAmount,
          error: function(m, err) {
            return console.log(err);
          },
          success: function(m, resp) {
            console.log('success', m, resp);
            return _this.set('piggyBank', m.piggyBank);
          }
        });
      };

      return Model;

    })(Backbone.Model);
    Collection = (function(_super) {

      __extends(Collection, _super);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.model = Model;

      Collection.prototype.syncName = 'student';

      Collection.prototype._selected = [];

      Collection.prototype.fromDB = function(data) {
        var method, model, options;
        method = data.method, model = data.model, options = data.options;
        switch (method) {
          case 'online':
            return this.get(model._id).set('online', model.online);
        }
      };

      Collection.prototype.modelType = function() {
        return "students";
      };

      Collection.prototype.initialize = function() {
        var _this = this;
        return this.on('reset', function() {
          var id, _i, _len, _ref, _results;
          if (_this._selected) {
            _ref = _this._selected;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              id = _ref[_i];
              _results.push(_this.get(id).toggleSelect());
            }
            return _results;
          }
        });
      };

      Collection.prototype.selected = function() {
        return this.filter(function(s) {
          return s.isSelected();
        });
      };

      Collection.prototype.selectionState = function() {
        var selState;
        if (this.selectedFiltered().length === this.filtered().length) {
          selState = 'all';
        } else if (this.selectedFiltered().length === 0) {
          selState = 'none';
        } else {
          selState = 'some';
        }
        return selState;
      };

      Collection.prototype.filtered = function() {
        var _this = this;
        return this.filter(function(m) {
          var _ref;
          return m.match((_ref = _this.searchTerm) != null ? _ref : '');
        });
      };

      Collection.prototype.selectedFiltered = function() {
        return _.filter(this.filtered(), function(m) {
          return m.get('selected') === true;
        });
      };

      Collection.prototype.selectFiltered = function(setTo) {
        var student, _i, _len, _ref, _results;
        if (setTo == null) {
          setTo = true;
        }
        _ref = this.filtered();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          student = _ref[_i];
          _results.push(student.set('selected', setTo));
        }
        return _results;
      };

      Collection.prototype.toggleSelectFiltered = function() {
        if (this.selectedFiltered().length === this.filtered().length) {
          return this.selectFiltered(false);
        } else if (this.selectedFiltered().length === 0) {
          return this.selectFiltered(true);
        } else {
          return this.selectFiltered(false);
        }
      };

      return Collection;

    })(Backbone.Collection);
    UIState = (function(_super) {

      __extends(UIState, _super);

      function UIState() {
        return UIState.__super__.constructor.apply(this, arguments);
      }

      UIState.prototype.defaults = {
        currentListView: 'list',
        searchTerm: '',
        addMode: false
      };

      UIState.prototype.toggleAddMode = function() {
        this.set('addMode', this.get('addMode'));
        return this;
      };

      return UIState;

    })(Backbone.Model);
    Views.Main = (function(_super) {

      __extends(Main, _super);

      function Main() {
        return Main.__super__.constructor.apply(this, arguments);
      }

      Main.prototype.tagName = 'div';

      Main.prototype.className = 'student-main container';

      Main.prototype.initialize = function() {
        var _this = this;
        this.state = new UIState;
        this.searchBox = new top.App.Teacher.Views.SearchBox;
        this.collection.on('reset', this.render, this);
        this.collection.on('add', function(i) {
          _this.addItem(i, true);
          return _this.renderControls();
        });
        this.collection.on('remove', function() {
          return _this.renderControls();
        });
        this.collection.on('saved', function() {
          var fm;
          fm = new App.Teacher.Views.FlashMessage({
            message: 'changes saved',
            type: 'success',
            time: 1000
          });
          return fm.render();
        });
        this.state.on('change:adding', function(m, v) {
          return _this.quickAdd();
        });
        this.searchBox.on('change', function(v) {
          _this.collection.searchTerm = v;
          _this.renderControls();
          return _this.renderList();
        });
        return this.newItem = new Views.NewListItem({
          collection: this.collection
        });
      };

      Main.prototype.events = {
        'click .add-students': function() {
          return this.state.set('adding', !this.state.get('adding'));
        },
        'click .delete-students': function() {
          var dc;
          dc = new UI.ConfirmDelete({
            collection: this.collection
          });
          return dc.render().open();
        },
        'click .email-students': function() {
          var es;
          es = new Views.EmailStudents({
            collection: this.collection
          });
          return es.render().open();
        },
        'click .passwords': function() {
          var pws;
          pws = new Views.Passwords({
            collection: this.collection
          });
          return pws.render();
        },
        'click .toggle-select-all': function() {
          return this.collection.toggleSelectFiltered();
        }
      };

      Main.prototype.selectIcons = {
        'all': 'check',
        'none': 'check-empty',
        'some': 'reorder'
      };

      Main.prototype.selectStrings = {
        'all': 'Unselect all',
        'none': 'Select all',
        'some': 'Unselect all'
      };

      Main.prototype.search = function(e) {
        var _this = this;
        clearTimeout(this.searchWait);
        return this.searchWait = wait(200, function() {
          return _this.state.set('searchTerm', $(e.target).val());
        });
      };

      Main.prototype.quickAdd = function() {
        if (this.state.get('adding')) {
          this.newItem.render().open(this.$('.new-item-cont'));
          this.newItem.focus();
          return this.newItem.delegateEvents();
        } else {
          return this.newItem.remove();
        }
      };

      Main.prototype.controlsTemplate = function() {
        return div({
          "class": 'btn-toolbar span12'
        }, function() {
          div({
            "class": 'btn-group pull-left'
          }, function() {
            var selState;
            return button({
              "class": "btn btn-mini pull-left icon-" + this.selectIcons[selState = this.collection.selectionState()] + " toggle-select-all"
            }, " " + this.selectStrings[selState]);
          });
          div({
            "class": 'btn-group pull-right'
          }, function() {
            return button({
              "class": "btn btn-mini btn-success icon-plus add-students " + (this.state.get('adding') ? 'active' : ''),
              'data-toggle': 'button'
            }, ' Quick add');
          });
          if (this.collection.selected().length) {
            div({
              "class": 'btn-group pull-left'
            }, function() {
              button({
                "class": 'btn btn-mini btn-info icon-envelope email-students'
              }, ' Email');
              button({
                "class": 'btn btn-mini btn-warning icon-key passwords'
              }, ' Passwords');
              return button({
                "class": 'btn btn-mini icon-heart heartbeats'
              }, ' Heartbeats');
            });
            return div({
              "class": 'btn-group pull-right'
            }, function() {
              return button({
                "class": 'btn btn-mini btn-danger icon-trash delete-students'
              }, ' Delete');
            });
          }
        });
      };

      Main.prototype.template = function() {
        div({
          "class": 'controls-cont row'
        }, function() {});
        return table({
          "class": 'list-cont table'
        }, function() {
          thead({
            "class": 'new-item-cont'
          });
          return tbody({
            "class": 'list'
          }, function() {});
        });
      };

      Main.prototype.addItem = function(stu, prepend) {
        var v;
        if (prepend == null) {
          prepend = false;
        }
        v = new Views.ListItem({
          model: stu,
          collection: this.collection
        });
        v.render();
        if (prepend) {
          v.$el.prependTo(this.$('.list'));
        } else {
          v.$el.appendTo(this.$('.list'));
        }
        return stu.on('change:selected', this.renderControls, this);
      };

      Main.prototype.renderControls = function() {
        this.$('.controls-cont').html(ck.render(this.controlsTemplate, this));
        return this;
      };

      Main.prototype.renderList = function() {
        var stu, _i, _len, _ref, _ref1;
        this.$('.list').empty();
        _ref1 = (_ref = this.collection.filtered()) != null ? _ref : this.collection.models;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          stu = _ref1[_i];
          this.addItem(stu);
        }
        return this.quickAdd();
      };

      Main.prototype.render = function() {
        this.$el.html(ck.render(this.template, this));
        this.$('.message').alert('close');
        this.renderList();
        this.renderControls();
        this.searchBox.setElement($('input#search-box')[0]);
        this.delegateEvents();
        return this;
      };

      return Main;

    })(Backbone.View);
    Views.NewListItem = (function(_super) {

      __extends(NewListItem, _super);

      function NewListItem() {
        this.clearErrors = __bind(this.clearErrors, this);

        this.showErrors = __bind(this.showErrors, this);
        return NewListItem.__super__.constructor.apply(this, arguments);
      }

      NewListItem.prototype.tagName = 'tr';

      NewListItem.prototype.className = 'list-item';

      NewListItem.prototype.initialize = function() {};

      NewListItem.prototype.events = {
        'click .add-item': 'addItem',
        'keydown input.email': function(e) {
          var _ref;
          console.log(e.which + ' pressed');
          if (((_ref = e.which) === 9 || _ref === 13) && !e.shiftKey) {
            console.log('calling additem');
            return this.addItem();
          }
        }
      };

      NewListItem.prototype.showErrors = function(model, errObj) {
        var err, fieldEl, fieldName, _ref, _results;
        _ref = errObj.errors;
        _results = [];
        for (fieldName in _ref) {
          err = _ref[fieldName];
          fieldEl = this.$("input." + fieldName);
          fieldEl.addClass('err');
          this.$(".control-group." + fieldName + " .help-block").text("" + err.type);
          _results.push(fieldEl.focus());
        }
        return _results;
      };

      NewListItem.prototype.clearErrors = function(x, y) {
        this.$('.control-group .help-block').text('');
        this.collection.trigger('saved');
        return this.clear().focus();
      };

      NewListItem.prototype.focus = function() {
        return this.$('input:first').focus();
      };

      NewListItem.prototype.addItem = function() {
        return this.collection.create({
          name: this.$('input.name').val(),
          email: this.$('input.email').val()
        }, {
          wait: true,
          error: this.showErrors,
          success: this.clearErrors
        });
      };

      NewListItem.prototype.clear = function() {
        this.$('input.name').val('');
        this.$('input.email').val('');
        return this;
      };

      NewListItem.prototype.template = function() {
        td(function() {
          return i({
            "class": 'icon-caret-right'
          });
        });
        td(function() {
          return i({
            "class": 'icon-user'
          });
        });
        td(function() {
          return div({
            "class": 'control-group name'
          }, function() {
            input({
              type: 'text',
              placeholder: 'name',
              "class": 'name'
            });
            return span({
              "class": 'help-block'
            });
          });
        });
        td(function() {
          return div({
            "class": 'control-group email'
          }, function() {
            input({
              type: 'text',
              placeholder: 'email',
              "class": 'email'
            });
            return span({
              "class": 'help-block'
            });
          });
        });
        td(function() {});
        return td(function() {
          return i({
            "class": 'icon-plus add-item'
          });
        });
      };

      NewListItem.prototype.render = function() {
        NewListItem.__super__.render.call(this);
        console.log('render called');
        return this;
      };

      return NewListItem;

    })(Backbone.View);
    Views.ListItem = (function(_super) {

      __extends(ListItem, _super);

      function ListItem() {
        this.clearErrors = __bind(this.clearErrors, this);

        this.showErrors = __bind(this.showErrors, this);
        return ListItem.__super__.constructor.apply(this, arguments);
      }

      ListItem.prototype.tagName = 'tr';

      ListItem.prototype.className = 'list-item';

      ListItem.prototype.initialize = function() {
        var _this = this;
        this.model.on('change', function() {
          return _this.render();
        });
        return this.model.on('remove', this.remove, this);
      };

      ListItem.prototype.events = {
        'click .select-item': function() {
          return this.model.toggleSelect();
        },
        'click .delete-item': function() {
          var dc;
          dc = new UI.ConfirmDelete({
            model: this.model
          });
          return dc.render().open();
        },
        'click .manage-password': function() {
          var managePassword;
          managePassword = new Views.ManagePassword({
            model: this.model
          });
          return managePassword.render().open();
        },
        'change input': function() {
          return this.model.save({
            name: this.$('input.name').val(),
            email: this.$('input.email').val()
          }, {
            error: this.showErrors,
            success: this.clearErrors
          });
        },
        'click .inc-piggyBank': function() {
          console.log('inc', this.model);
          return this.model.changePennies(5);
        },
        'click .dec-piggyBank': function() {
          return this.model.changePennies(-5);
        },
        'click .signin-as': function() {
          return this.model.getLoginKey(function(err, key) {
            return alert(err, key);
          });
        }
      };

      ListItem.prototype.showErrors = function(model, errObj) {
        var err, fieldEl, fieldName, _ref, _results;
        console.log(model, errObj);
        _ref = errObj.errors;
        _results = [];
        for (fieldName in _ref) {
          err = _ref[fieldName];
          fieldEl = this.$("input." + fieldName);
          fieldEl.addClass('err');
          this.$(".control-group." + fieldName + " .help-block").text("" + err.type);
          _results.push(fieldEl.focus());
        }
        return _results;
      };

      ListItem.prototype.clearErrors = function(x, y) {
        this.$('.control-group .help-block').text('');
        return this.model.collection.trigger('saved');
      };

      ListItem.prototype.heartBeat = function() {
        var _this = this;
        this.$('.icon-heart').addClass('beat');
        return wait(500, function() {
          return _this.$('.icon-heart').removeClass('beat');
        });
      };

      ListItem.prototype.template = function() {
        td(function() {
          return i({
            "class": "" + (this.isSelected() ? 'icon-check' : 'icon-check-empty') + " select-item"
          });
        });
        td(function() {
          return i({
            "class": 'icon-user'
          });
        });
        td(function() {
          return div({
            "class": 'control-group name'
          }, function() {
            input({
              type: 'text',
              value: "" + (this.get('name')),
              placeholder: 'name',
              "class": 'name'
            });
            return span({
              "class": 'help-block name'
            });
          });
        });
        td(function() {
          return div({
            "class": 'control-group email'
          }, function() {
            input({
              type: 'text',
              value: "" + (this.get('email')),
              placeholder: 'email',
              "class": 'email'
            });
            return span({
              "class": 'help-block email'
            });
          });
        });
        td(function() {
          span({
            "class": "piggy-bank pull-left icon-heart " + (this.get('online') ? 'online' : '')
          }, " " + (this.get('piggyBank')));
          return span({
            "class": 'btn-group'
          }, function() {
            button({
              "class": 'btn btn-mini icon-plus inc-piggyBank'
            });
            return button({
              "class": 'btn btn-mini icon-minus dec-piggyBank'
            });
          });
        });
        return td(function() {
          return span({
            "class": 'btn-group'
          }, function() {
            button({
              "class": 'btn btn-mini manage-password icon-key'
            });
            button({
              "class": 'btn btn-mini send-email icon-envelope'
            });
            button({
              "class": 'btn btn-mini delete-item icon-trash'
            });
            return button({
              "class": 'btn btn-mini signin-as icon-signin'
            });
          });
        });
      };

      ListItem.prototype.render = function() {
        ListItem.__super__.render.call(this);
        if (this.model.isSelected()) {
          this.$el.addClass('selected');
        } else {
          this.$el.removeClass('selected');
        }
        this.$('input').tooltip();
        return this;
      };

      return ListItem;

    })(Backbone.View);
    Views.ManagePassword = (function(_super) {

      __extends(ManagePassword, _super);

      function ManagePassword() {
        return ManagePassword.__super__.constructor.apply(this, arguments);
      }

      ManagePassword.prototype.tagName = 'div';

      ManagePassword.prototype.className = 'modal manage-password-view hide fade';

      ManagePassword.prototype.initialize = function() {
        this.$el.modal();
        return this.model.on('change:password', this.render, this);
      };

      ManagePassword.prototype.chargeEmailButton = function() {
        var _this = this;
        return this.$('.send-pw').one('click', function(e) {
          console.log('clicked');
          $(e.target).off().addClass('disabled').text(' Sending...');
          return _this.model.sync('email', {
            _id: _this.model.id
          }, {
            subject: 'your password',
            html: "your password is " + (_this.model.get('password')),
            error: function(model, err) {
              return console.log(model, err);
            },
            success: function() {
              return $(e.target).removeClass('icon-envelope').addClass('icon-ok').removeClass('btn-info').addClass('btn-success').addClass('disabled').text(' Email sent!');
            }
          });
        });
      };

      ManagePassword.prototype.events = {
        'click .generate-pw': function() {
          return this.model.save({
            password: '*'
          }, {
            regenerate: true
          });
        }
      };

      ManagePassword.prototype.template = function() {
        div({
          "class": 'modal-body'
        }, function() {
          span({
            "class": 'icon-key pw'
          }, " " + (this.get('password')));
          return span("  is " + (this.get('name')) + "'s password.");
        });
        return div({
          "class": 'modal-footer'
        }, function() {
          return div({
            "class": 'btn-toolbar'
          }, function() {
            div({
              "class": 'btn-group'
            }, function() {
              return button({
                "class": 'btn btn-info icon-envelope send-pw'
              }, " Email password to " + (this.get('name')));
            });
            div({
              "class": 'btn-group'
            }, function() {
              return button({
                "class": 'btn btn-warning icon-refresh generate-pw'
              }, " Generate a new one");
            });
            return div({
              "class": 'btn-group'
            }, function() {
              return button({
                "class": 'btn',
                'data-dismiss': 'modal'
              }, "Close");
            });
          });
        });
      };

      ManagePassword.prototype.render = function() {
        this.$el.html(ck.render(this.template, this.model));
        this.chargeEmailButton();
        return this;
      };

      return ManagePassword;

    })(Backbone.View);
    Views.Passwords = (function(_super) {

      __extends(Passwords, _super);

      function Passwords() {
        return Passwords.__super__.constructor.apply(this, arguments);
      }

      Passwords.prototype.tagName = 'div';

      Passwords.prototype.className = 'modal fade hide';

      Passwords.prototype.initialize = function() {
        var _this = this;
        return this.collection.on('reset', function() {
          return _this.renderList();
        });
      };

      Passwords.prototype.events = {
        'click .generate-pws': 'generatePws',
        'click .email-pws': 'emailPws'
      };

      Passwords.prototype.generatePws = function() {
        var _this = this;
        this.collection._selected = _.pluck(this.collection.selected(), 'id');
        return this.collection.sync('changePasswords', null, {
          ids: _.pluck(this.collection.selected(), 'id'),
          error: function(m, e) {
            return console.log('error', m, e);
          },
          success: function(m, e) {
            return _this.collection.fetch();
          }
        });
      };

      Passwords.prototype.emailPws = function() {
        var html,
          _this = this;
        html = "<p>Hello, {name}!\n</p>\n<p>\nHere is your password: {password}\n<br/>\nClick <a href='http://lingualab.io' >here to sign in</a>.\n</p>\n<b>Bye!</b>";
        return this.collection.sync('email', null, {
          ids: _.pluck(this.collection.selected(), 'id'),
          subject: 'Your password',
          html: html,
          error: function(m, e) {
            return console.log('error', m, e);
          },
          success: function(m, e) {
            return console.log('success');
          }
        });
      };

      Passwords.prototype.listTemplate = function() {
        var stu, _i, _len, _ref, _results;
        _ref = this.selected();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          stu = _ref[_i];
          _results.push(tr(function() {
            td("" + (stu.get('name')) + " (" + (stu.get('email')) + ")");
            return td({
              "class": 'pw icon-key'
            }, " " + (stu.get('password')));
          }));
        }
        return _results;
      };

      Passwords.prototype.template = function() {
        div({
          "class": 'modal-header'
        }, function() {
          return h3('Manage passwords');
        });
        div({
          "class": 'modal-body'
        }, function() {
          return table({
            "class": 'table'
          }, function() {});
        });
        return div({
          "class": 'modal-footer'
        }, function() {
          return div({
            "class": 'btn-toolbar'
          }, function() {
            button({
              "class": 'btn btn-info icon-envelope email-pws'
            }, ' Email passwords');
            button({
              "class": 'btn btn-warning icon-key generate-pws'
            }, ' Generate new passwords');
            return button({
              "class": 'btn',
              'data-dismiss': 'modal'
            }, ' Close');
          });
        });
      };

      Passwords.prototype.renderList = function() {
        this.$('table').html(ck.render(this.listTemplate, this.collection));
        return this;
      };

      Passwords.prototype.render = function() {
        Passwords.__super__.render.call(this);
        this.renderList();
        this.$el.modal('show');
        return this;
      };

      return Passwords;

    })(Backbone.View);
    Views.EmailStudents = (function(_super) {

      __extends(EmailStudents, _super);

      function EmailStudents() {
        return EmailStudents.__super__.constructor.apply(this, arguments);
      }

      EmailStudents.prototype.tagName = 'div';

      EmailStudents.prototype.className = 'modal hide fade emailer-view';

      EmailStudents.prototype.templates = {
        'password': "<p>Hello, <span class=\"template-field\" data-fld=\"name\">name</span>!\n</p>\n<p>\nHere is your password: <span class=\"template-field\" data-fld=\"password\">password</span>\n<br/>\nClick <a href='http://lingualab.io' >here to sign in</a>.\n</p>\n<b>Bye!</b>",
        'praise': "<p>Hello, <span class=\"template-field\" data-fld=\"name\">name</span>!</p>\n<p>\nYou've been working hard outside of class. I just wanted to let you know that I\nsee how much you've been practicing this week. Great job! Keep it up, I promise it'll pay off for you!\n</p>"
      };

      EmailStudents.prototype.initialize = function() {};

      EmailStudents.prototype.document = document;

      EmailStudents.prototype.events = {
        'click .bold': 'bold',
        'click .italic': 'italic',
        'click .underline': 'underline',
        'click .link': 'link',
        'click .size': 'size',
        'click ul.insert-data a': 'insertFld',
        'click .send-emails': 'sendEmails',
        'click .load-template': 'loadTemplate'
      };

      EmailStudents.prototype.sendEmails = function() {
        var _this = this;
        return this.collection.sync('email', null, {
          ids: _.pluck(this.collection.selected(), 'id'),
          subject: "important email from " + (top.app.data.teacher.get('teacherName')),
          html: this.simplifiedHTML(),
          error: function(m, e) {
            return console.log('error', m, e);
          },
          success: function(m, e) {
            return console.log('success');
          }
        });
      };

      EmailStudents.prototype.simplifiedHTML = function() {
        var body;
        body = this.$('.editor-area').html();
        body = body.replace(/<span class=.template-field. data-fld=.([^"]+).>[^<]*<\/span>/g, "{$1}");
        console.log(body);
        return body;
      };

      EmailStudents.prototype.getSelectedText = function() {
        var _ref;
        if ((_ref = this.document) != null ? _ref.selection : void 0) {
          return document.selection.createRange().text;
        } else if (this.document) {
          return document.getSelection().toString();
        }
      };

      EmailStudents.prototype.selectTest = function() {
        if (this.getSelectedText().length === 0) {
          alert('Select some text first.');
          return false;
        }
        return true;
      };

      EmailStudents.prototype.exec = function(type, arg) {
        if (arg == null) {
          arg = null;
        }
        return this.document.execCommand(type, false, arg);
      };

      EmailStudents.prototype.query = function(type) {
        return this.document.queryCommandValue(type);
      };

      EmailStudents.prototype.bold = function(e) {
        e.preventDefault();
        return this.exec('bold');
      };

      EmailStudents.prototype.italic = function(e) {
        e.preventDefault();
        return this.exec('italic');
      };

      EmailStudents.prototype.underline = function(e) {
        e.preventDefault();
        return this.exec('underline');
      };

      EmailStudents.prototype.list = function(e) {
        e.preventDefault();
        return this.exec('insertUnorderedList');
      };

      EmailStudents.prototype.link = function(e) {
        var href;
        e.preventDefault();
        this.exec('unlink');
        href = prompt('Enter a link:', 'http://');
        if (!href || href === 'http://') {
          return;
        }
        if (!/:\/\//.test(href)) {
          href = 'http://' + href;
        }
        return this.exec('createLink', href);
      };

      EmailStudents.prototype.insertFld = function(e) {
        var fld, label;
        console.log(e.currentTarget);
        e.preventDefault();
        fld = $(e.currentTarget).attr('data-fld');
        label = $(e.currentTarget).attr('data-label');
        return this.exec('insertHTML', "&nbsp;<span class='template-field' data-fld='" + fld + "' contenteditable=false>" + label + "</span>&nbsp;");
      };

      EmailStudents.prototype.size = function(e) {
        e.preventDefault();
        return this.exec('fontSize', $(e.target).attr('data-size'));
      };

      EmailStudents.prototype.loadTemplate = function(e) {
        e.preventDefault();
        return this.$('.editor-area').html(this.templates[$(e.currentTarget).attr('data-template')]);
      };

      EmailStudents.prototype.template = function() {
        div({
          "class": 'modal-header'
        }, function() {
          return div({
            "class": 'btn-toolbar'
          }, function() {
            div({
              "class": 'btn-group'
            }, function() {
              button({
                "class": 'btn icon-bold bold'
              });
              button({
                "class": 'btn icon-italic italic'
              });
              button({
                "class": 'btn icon-underline underline'
              });
              button({
                "class": 'btn icon-link link'
              });
              a({
                "class": "btn dropdown-toggle icon-text-height",
                'data-toggle': "dropdown",
                href: "#"
              }, function() {
                return span({
                  "class": 'caret'
                });
              });
              return ul({
                "class": 'dropdown-menu'
              }, function() {
                li(function() {
                  return a({
                    href: '#',
                    "class": 'size',
                    'data-size': 2
                  }, 'small');
                });
                li(function() {
                  return a({
                    href: '#',
                    "class": 'size',
                    'data-size': 4
                  }, 'medium');
                });
                return li(function() {
                  return a({
                    href: '#',
                    "class": 'size',
                    'data-size': 5
                  }, 'large');
                });
              });
            });
            div({
              "class": 'btn-group'
            }, function() {
              a({
                "class": 'btn dropdown-toggle icon-user',
                'data-toggle': 'dropdown',
                href: '#'
              }, function() {
                span(" Student info ");
                return span({
                  "class": 'caret'
                });
              });
              return ul({
                "class": 'dropdown-menu insert-data'
              }, function() {
                li(function() {
                  return a({
                    href: '#',
                    "class": 'insert-name',
                    'data-label': 'name',
                    'data-fld': 'name'
                  }, function() {
                    i({
                      "class": 'icon-credit-card'
                    });
                    return span(' Name');
                  });
                });
                li(function() {
                  return a({
                    href: '#',
                    "class": 'insert-email',
                    'data-label': 'email address',
                    'data-fld': 'email'
                  }, function() {
                    return span('@ Email Address');
                  });
                });
                li(function() {
                  return a({
                    href: '#',
                    "class": 'insert-password',
                    'data-label': 'password',
                    'data-fld': 'password'
                  }, function() {
                    i({
                      "class": 'icon-key'
                    });
                    return span(' Password');
                  });
                });
                li(function() {
                  return a({
                    href: '#',
                    "class": 'insert-signin',
                    'data-label': 'instant sign-in link (good for 10m)',
                    'data-fld': 'signin-link'
                  }, function() {
                    i({
                      "class": 'icon-signin'
                    });
                    return span(' Instant sign in link');
                  });
                });
                return li(function() {
                  return a({
                    href: '#',
                    "class": 'insert-time',
                    'data-label': 'practice time this week',
                    'data-fld': 'time-week'
                  }, function() {
                    i({
                      "class": 'icon-time'
                    });
                    return span(' Time spent practicing this week');
                  });
                });
              });
            });
            return div({
              "class": 'btn-group'
            }, function() {
              a({
                "class": 'btn dropdown-toggle',
                'data-toggle': 'dropdown',
                href: '#'
              }, function() {
                i({
                  "class": 'icon-file'
                });
                span(' Templates ');
                return span({
                  "class": 'caret'
                });
              });
              return ul({
                "class": 'dropdown-menu'
              }, function() {
                li(function() {
                  return a({
                    href: '#',
                    "class": 'load-template',
                    'data-template': 'password'
                  }, function() {
                    i({
                      "class": 'icon-key'
                    });
                    return span(' Send passwords');
                  });
                });
                li(function() {
                  return a({
                    href: '#',
                    "class": 'load-template',
                    'data-template': 'praise'
                  }, function() {
                    i({
                      "class": 'icon-thumbs-up'
                    });
                    return span(' Praise');
                  });
                });
                return li(function() {
                  return a({
                    href: '#',
                    "class": 'load-template',
                    'data-template': 'reminder'
                  }, function() {
                    i({
                      "class": 'icon-pushpin'
                    });
                    return span(' Reminder');
                  });
                });
              });
            });
          });
        });
        div({
          "class": 'modal-body'
        }, function() {
          return div({
            "class": 'editor-area'
          }, function() {});
        });
        return div({
          "class": 'modal-footer'
        }, function() {
          button({
            "class": 'btn pull-right',
            'data-dismiss': 'modal'
          }, "Close");
          return button({
            "class": 'btn btn-info icon-envelope send-emails pull-left'
          }, " Send it to " + (this.selected().length) + " students");
        });
      };

      EmailStudents.prototype.render = function() {
        var _this = this;
        EmailStudents.__super__.render.call(this);
        this.$el.modal('show');
        this.$el.on('shown', function() {
          _this.trigger('ready');
          _this.$('.editor-area').attr('contenteditable', true);
          return _this.$('.editor-area').focus();
        });
        return this;
      };

      return EmailStudents;

    })(Backbone.View);
    Views.Detail = (function(_super) {

      __extends(Detail, _super);

      function Detail() {
        return Detail.__super__.constructor.apply(this, arguments);
      }

      Detail.prototype.tagName = 'div';

      Detail.prototype.className = 'detail';

      Detail.prototype.initialize = function() {};

      Detail.prototype.showErrors = function(model, errs) {
        var err, type, _ref, _results;
        console.log(errs);
        _ref = errs.errors;
        _results = [];
        for (type in _ref) {
          err = _ref[type];
          this.$(".control-group." + type).addClass('error');
          _results.push(this.$(".control-group." + type + " .help-block").text(err.type));
        }
        return _results;
      };

      Detail.prototype.events = {
        'keyup .name': function() {
          var _ref, _ref1;
          return this.$('.full-name').text(" " + ((_ref = this.$('input.firstName').val()) != null ? _ref : '') + " " + ((_ref1 = this.$('input.lastName').val()) != null ? _ref1 : ''));
        },
        'click .save': function() {
          var fld, model, _i, _len, _ref,
            _this = this;
          model = {};
          _ref = this.$('.fld');
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            fld = _ref[_i];
            model[$(fld).attr('data-fld')] = $(fld).val();
          }
          return this.model.save(model, {
            error: function(model, errs) {
              return _this.showErrors(model, errs);
            },
            success: function() {
              return top.app.router.navigate('students', true);
            }
          });
        }
      };

      Detail.prototype.template = function() {
        div({
          "class": 'page-header'
        }, function() {
          var _ref;
          return h2({
            "class": 'icon-user icon-large full-name'
          }, " " + ((_ref = this.get('name')) != null ? _ref : ''));
        });
        fieldset(function() {
          div({
            "class": 'control-group name'
          }, function() {
            var _ref;
            input({
              type: 'text',
              "class": 'fld firstName name',
              'data-fld': 'name',
              placeholder: 'Name',
              value: "" + ((_ref = this.get('name')) != null ? _ref : '')
            });
            return span({
              "class": 'help-block'
            });
          });
          div({
            "class": 'control-group email'
          }, function() {
            div({
              "class": 'input-prepend'
            }, function() {
              var _ref;
              span({
                "class": 'add-on'
              }, function() {
                return i({
                  "class": 'icon-envelope'
                });
              });
              return input({
                type: 'text',
                "class": 'fld email',
                'data-fld': 'email',
                placeholder: 'email',
                value: "" + ((_ref = this.get('email')) != null ? _ref : '')
              });
            });
            return span({
              "class": 'help-block'
            });
          });
          return div({
            "class": 'control-group password'
          }, function() {
            div({
              "class": 'input-prepend'
            }, function() {
              var _ref;
              span({
                "class": 'add-on'
              }, function() {
                return i({
                  "class": 'icon-key'
                });
              });
              input({
                type: 'text',
                "class": 'fld password',
                'data-fld': 'password',
                value: "" + ((_ref = this.get('password')) != null ? _ref : '')
              });
              return span(function() {
                var _ref1, _ref2;
                a({
                  href: '#',
                  rel: 'popover',
                  "class": 'password-toggle',
                  'data-content': "is " + ((_ref1 = this.get('firstName')) != null ? _ref1 : '') + "'s password",
                  'data-title': "" + ((_ref2 = this.get('password')) != null ? _ref2 : ''),
                  'data-placement': 'left'
                }, function() {});
                return i({
                  "class": 'icon-eye'
                });
              });
            });
            return span({
              "class": 'help-block'
            });
          });
        });
        div({
          "class": 'page-header'
        });
        return button({
          "class": 'save btn btn-success icon-check'
        }, ' Save changes');
      };

      return Detail;

    })(Backbone.View);
    return _ref = [Model, Collection, UIState], exports.Model = _ref[0], exports.Collection = _ref[1], exports.UIState = _ref[2], _ref;
  });

  module('App.Teacher', function(exports, top) {
    var Model, Views;
    Model = (function(_super) {

      __extends(Model, _super);

      function Model() {
        return Model.__super__.constructor.apply(this, arguments);
      }

      Model.prototype.idAttribute = '_id';

      Model.prototype.syncName = 'user';

      Model.prototype.fromDB = function(data) {
        var method, model, options;
        method = data.method, model = data.model, options = data.options;
        switch (method) {
          case 'piggyBank':
            return this.set('piggyBank', model.piggyBank);
        }
      };

      return Model;

    })(Backbone.Model);
    exports.Model = Model;
    exports.Views = Views = {};
    Views.FlashMessage = (function(_super) {

      __extends(FlashMessage, _super);

      function FlashMessage() {
        return FlashMessage.__super__.constructor.apply(this, arguments);
      }

      FlashMessage.prototype.tagName = 'div';

      FlashMessage.prototype.className = 'alert fade in flash-message';

      FlashMessage.prototype.initialize = function(options) {
        this.message = options.message;
        this.type = options.type;
        return this.time = options.time;
      };

      FlashMessage.prototype.render = function() {
        var _this = this;
        this.$el.text(this.message);
        this.$el.alert();
        this.$el.addClass("alert-" + this.type);
        this.$el.appendTo('body');
        this.$el.on('closed', function() {
          return _this.remove();
        });
        if (this.time) {
          return wait(this.time, function() {
            return _this.$el.alert('close');
          });
        }
      };

      return FlashMessage;

    })(Backbone.View);
    Views.Profile = (function(_super) {

      __extends(Profile, _super);

      function Profile() {
        return Profile.__super__.constructor.apply(this, arguments);
      }

      Profile.prototype.tagName = 'div';

      Profile.prototype.className = 'modal fade hide profile-view';

      Profile.prototype.initialize = function() {};

      Profile.prototype.events = {
        'change input, select': function(e) {
          var model;
          console.log('change');
          model = {};
          model[$(e.target).attr('data-fld')] = $(e.target).val();
          return this.model.save(model, {
            error: this.showErrors,
            success: this.saveSuccess
          });
        }
      };

      Profile.prototype.showErrors = function(model, errs) {
        var err, type, _ref, _results;
        console.log(errs);
        _ref = errs.errors;
        _results = [];
        for (type in _ref) {
          err = _ref[type];
          this.$(".control-group." + type).addClass('error');
          _results.push(this.$(".control-group." + type + " .help-block").text(err.type));
        }
        return _results;
      };

      Profile.prototype.saveSuccess = function() {
        var alert,
          _this = this;
        this.$('.control-group').removeClass('error');
        this.$('.control-group .help-block').text('');
        alert = $('<span/>').addClass('label-success').addClass('label').addClass('pull-left').text('Change saved!');
        alert.prependTo(this.$('.modal-footer'));
        return wait(1000, function() {
          return alert.remove();
        });
      };

      Profile.prototype.template = function() {
        div({
          "class": 'modal-header'
        }, function() {
          return h1(function() {
            img({
              src: "" + (this.get('twitterImg'))
            });
            return text(" " + (this.get('twitterName')));
          });
        });
        div({
          "class": 'modal-body'
        }, function() {
          return form(function() {
            div({
              "class": 'control-group teacherName'
            }, function() {
              label('How do students address you? (if different from your Twitter name above)');
              input({
                type: 'text',
                placeholder: 'your teacher name',
                'data-fld': 'teacherName',
                value: "" + (this.get('teacherName'))
              });
              return span({
                "class": 'help-block'
              });
            });
            div({
              "class": 'control-group email'
            }, function() {
              label('Enter an email address where you can be contacted (optional).');
              input({
                type: 'text',
                placeholder: 'your email',
                'data-fld': 'email',
                value: "" + (this.get('email'))
              });
              return span({
                "class": 'help-block'
              });
            });
            return div({
              "class": 'control-group emailPref'
            }, function() {
              label('When do you want to receive emails from lingualab.io?');
              return select({
                "class": 'email-pref',
                'data-fld': 'emailPref'
              }, function() {
                option({
                  value: 'never'
                }, 'Never!');
                option({
                  value: 'important'
                }, 'Important notifications only');
                return option({
                  value: 'features'
                }, 'Notifications, new features and tips');
              });
            });
          });
        });
        return div({
          "class": 'modal-footer'
        }, function() {
          return button('btn', {
            'data-dismiss': 'modal'
          }, 'Close');
        });
      };

      Profile.prototype.render = function() {
        var _this = this;
        Profile.__super__.render.call(this);
        this.$el.modal('show');
        this.$('select.email-pref').val(this.model.get('emailPref'));
        this.delegateEvents();
        this.$el.on('hidden', function() {
          return _this.remove();
        });
        return this;
      };

      return Profile;

    })(Backbone.View);
    Views.Account = (function(_super) {

      __extends(Account, _super);

      function Account() {
        return Account.__super__.constructor.apply(this, arguments);
      }

      Account.prototype.tagName = 'div';

      Account.prototype.className = 'modal fade hide account-view';

      Account.prototype.initialize = function() {};

      Account.prototype.events = {
        'click button.purchase': 'createToken'
      };

      Account.prototype.createToken = function() {
        var data,
          _this = this;
        data = {
          number: this.$('input.card-number').val(),
          cvc: this.$('input.card-cvc').val(),
          exp_month: this.$('input.card-expiry-month').val(),
          exp_year: this.$('input.card-expiry-year').val()
        };
        return Stripe.createToken(data, function(status, response) {
          console.log('stripe: ', status, response);
          if (response.error) {
            return _this.$('.errors').text(response.error.message);
          } else {
            console.log(_this.model.toJSON());
            return _this.model.sync('charge', _this.model.toJSON(), {
              charge: {
                amount: _this.$('.amount').val(),
                card: response.id,
                currency: 'usd',
                description: _this.model.id
              },
              error: function(m, err) {
                return console.log('charge error: ', m, err);
              },
              success: function(m, err) {
                return console.log('charge success: ', m, err);
              }
            });
          }
        });
      };

      Account.prototype.template = function() {
        div({
          "class": 'modal-header'
        }, function() {
          return h2('Account');
        });
        div({
          "class": 'modal-body'
        }, function() {
          h3("You currently have " + (this.get('piggyBank')));
          form({
            "class": 'form-inline'
          }, function() {
            return div({
              "class": 'control-group'
            }, function() {
              span("Purchase ");
              return input({
                type: 'text',
                "class": 'input-mini amount'
              });
            });
          });
          form({
            "class": 'cc'
          }, function() {
            div({
              "class": 'control-group card-number'
            }, function() {
              input({
                type: 'text',
                "class": 'fld card-number',
                'data-fld': 'card-number',
                placeholder: 'credit card number',
                autocomplete: 'off',
                size: 20
              });
              return span({
                "class": 'help-block'
              });
            });
            div({
              "class": 'control-group card-cvc'
            }, function() {
              input({
                type: 'text',
                "class": 'fld card-cvc input-mini',
                'data-fld': 'card-cvc',
                placeholder: 'CVCC',
                autocomplete: 'off',
                size: 4
              });
              return span({
                "class": 'help-block'
              });
            });
            div({
              "class": 'control-group card-expiry-month'
            }, function() {
              input({
                type: 'text',
                "class": 'fld input-mini card-expiry-month',
                'data-fld': 'card-expiry-month',
                placeholder: 'MM',
                autocomplete: 'off',
                size: '2'
              });
              return span({
                "class": 'help-block'
              });
            });
            return div({
              "class": 'control-group card-expiry-year'
            }, function() {
              input({
                type: 'text',
                "class": 'fld input-small card-expiry-year',
                'data-fld': 'card-expiry-year',
                placeholder: 'YYYY',
                autocomplete: 'off',
                size: '4'
              });
              return span({
                "class": 'help-block'
              });
            });
          });
          return div({
            "class": 'errors'
          }, function() {});
        });
        return div({
          "class": 'modal-footer'
        }, function() {
          button({
            "class": 'btn-success btn icon-credit-card purchase pull-left btn-large icon-large'
          }, " Purchase");
          return button({
            "class": 'btn',
            'data-dismiss': 'modal'
          }, ' Close');
        });
      };

      Account.prototype.render = function() {
        var _this = this;
        Account.__super__.render.call(this);
        this.$el.modal('show');
        this.delegateEvents();
        this.$el.on('hidden', function() {
          return _this.remove();
        });
        return this;
      };

      return Account;

    })(Backbone.View);
    Views.SearchBox = (function(_super) {

      __extends(SearchBox, _super);

      function SearchBox() {
        return SearchBox.__super__.constructor.apply(this, arguments);
      }

      SearchBox.prototype.events = {
        'keyup': function(e) {
          var _this = this;
          console.log(e.which);
          clearTimeout(this.searchWait);
          return this.searchWait = wait(200, function() {
            return _this.trigger('change', $(e.target).val());
          });
        }
      };

      SearchBox.prototype.initialize = function() {
        this.el = $('input#search-box')[0];
        return this.delegateEvents();
      };

      return SearchBox;

    })(Backbone.View);
    return Views.TopBar = (function(_super) {

      __extends(TopBar, _super);

      function TopBar() {
        return TopBar.__super__.constructor.apply(this, arguments);
      }

      TopBar.prototype.tagName = 'div';

      TopBar.prototype.className = 'top-bar navbar navbar-fixed-top';

      TopBar.prototype.initialize = function() {
        var _this = this;
        return this.model.on('change:piggyBank', function(m, v) {
          console.log('piggyBank change:', v);
          return _this.$('.piggyBank').text(v);
        });
      };

      TopBar.prototype.events = {
        'click .profile': function(e) {
          console.log('profile');
          top.app.views.profile.render();
          return false;
        },
        'click .heart': function(e) {
          top.app.views.piggy.render();
          return false;
        }
      };

      TopBar.prototype.updateNav = function(rt) {
        this.$('ul.nav li').removeClass('active');
        this.$("ul.nav a[href=#" + rt + "]").parent('li').addClass('active');
        return this;
      };

      TopBar.prototype.template = function() {
        return div({
          "class": 'navbar-inner'
        }, function() {
          return div({
            "class": 'container'
          }, function() {
            a({
              "class": 'btn btn-navbar',
              'data-toggle': 'collapse',
              'data-target': '.nav-collapse'
            }, function() {
              span({
                "class": 'icon-beaker icon-large'
              });
              return span({
                "class": 'icon-reorder icon-large'
              });
            });
            return div({
              "class": 'nav-collapse'
            }, function() {
              ul({
                "class": 'nav'
              }, function() {
                li(function() {
                  return a({
                    "class": 'brand pull-left',
                    href: '#'
                  }, function() {
                    return i({
                      "class": 'icon-bolt'
                    });
                  });
                });
                li({
                  "class": 'divider-vertical'
                });
                li(function() {
                  return a({
                    href: '#files'
                  }, function() {
                    i({
                      "class": 'icon-briefcase'
                    });
                    return text(' Files');
                  });
                });
                li(function() {
                  return a({
                    href: '#students'
                  }, function() {
                    i({
                      "class": 'icon-group'
                    });
                    return text(' Students');
                  });
                });
                return li(function() {
                  return a({
                    href: '#lab'
                  }, function() {
                    i({
                      "class": 'icon-headphones'
                    });
                    return text(' Lab');
                  });
                });
              });
              return ul({
                "class": 'nav pull-right'
              }, function() {
                li({
                  "class": 'pull-left'
                }, function() {
                  return form({
                    "class": 'navbar-search pull-left'
                  }, function() {
                    return input({
                      type: 'text',
                      id: 'search-box',
                      "class": 'search-query span2',
                      placeholder: 'search'
                    });
                  });
                });
                li({
                  "class": 'divider-vertical'
                });
                li(function() {
                  return a({
                    "class": 'user profile',
                    href: '#'
                  }, function() {
                    return img({
                      src: "" + (this.get('twitterImg'))
                    });
                  });
                });
                li(function() {
                  return a({
                    href: '#',
                    "class": 'heart'
                  }, function() {
                    i({
                      "class": 'icon-heart'
                    });
                    return span({
                      "class": 'piggyBank'
                    }, " " + (this.get('piggyBank')));
                  });
                });
                li({
                  "class": 'divider-vertical'
                });
                return li(function() {
                  return a({
                    href: '/logout',
                    "class": 'icon-signout'
                  });
                });
              });
            });
          });
        });
      };

      TopBar.prototype.render = function() {
        this.$el.html(ck.render(this.template, this.model));
        return this;
      };

      return TopBar;

    })(Backbone.View);
  });

  module('App', function(exports, top) {
    var Model, Router, _ref;
    Model = (function() {

      function Model() {
        var fetcher,
          _this = this;
        window.filepicker.setKey('Ag4e6fVtyRNWgXY2t3Dccz');
        Stripe.setPublishableKey('pk_04LnDZEuRgae5hqjKjFaWjFyTYFgs');
        this.socketConnect();
        this.fromDB();
        this.data = {
          teacher: new App.Teacher.Model(top.data.session.user),
          filez: new App.File.Collection(),
          students: new App.Student.Collection(),
          labs: new App.Lab.Collection()
        };
        this.views = {
          topBar: new App.Teacher.Views.TopBar({
            model: this.data.teacher
          }),
          filez: new App.File.Views.Main({
            collection: this.data.filez
          }),
          students: new App.Student.Views.Main({
            collection: this.data.students
          }),
          profile: new App.Teacher.Views.Profile({
            model: this.data.teacher
          }),
          piggy: new App.Teacher.Views.Account({
            model: this.data.teacher
          })
        };
        this.router = new Router(this.data, this.views);
        this.fetched = 0;
        fetcher = function(col) {
          return col.fetch({
            success: function() {
              _this.fetched++;
              if (_this.fetched === (_.keys(_this.data)).length - 1) {
                return Backbone.history.start();
              }
            }
          });
        };
        wait(200, function() {
          fetcher(_this.data.filez);
          fetcher(_this.data.students);
          return fetcher(_this.data.labs);
        });
      }

      Model.prototype.fromDB = function() {
        var _this = this;
        return this.connection.on('sync', function(service, data) {
          console.log('service', service, 'data', data);
          switch (service) {
            case 'file':
              return _this.data.filez.fromDB(data);
            case 'student':
              return _this.data.students.fromDB(data);
            case 'user':
              return _this.data.teacher.fromDB(data);
          }
        });
      };

      Model.prototype.socketConnect = function() {
        this.connection = window.sock = window.io.connect("https://" + window.data.CFG.API.HOST);
        return this.connectionView = new App.Connection.Views.Main({
          model: this.connection
        });
      };

      return Model;

    })();
    Router = (function(_super) {

      __extends(Router, _super);

      function Router() {
        return Router.__super__.constructor.apply(this, arguments);
      }

      Router.prototype.initialize = function(data, views) {
        this.data = data;
        this.views = views;
        return this.showTopBar();
      };

      Router.prototype.routes = {
        '/': 'home',
        'files': 'files',
        'students': 'students',
        'lab': 'lab',
        'lab/:id': 'loadLab'
      };

      Router.prototype.showTopBar = function() {
        return this.views.topBar.render().open();
      };

      Router.prototype.home = function() {
        return this.clearViews();
      };

      Router.prototype.profile = function() {
        return this.views.profile.render();
      };

      Router.prototype.files = function() {
        this.clearViews('topBar');
        this.views.topBar.updateNav('files');
        return this.views.filez.render().open();
      };

      Router.prototype.fileDetail = function(id) {
        this.clearViews('topBar');
        this.views.detail = new App.File.Views.Detail({
          model: this.data.filez.get(id)
        });
        return this.views.detail.render().open();
      };

      Router.prototype.students = function() {
        this.clearViews('topBar');
        this.views.topBar.updateNav('students');
        return this.views.students.render().open();
      };

      Router.prototype.lab = function() {
        this.clearViews('topBar');
        this.views.topBar.updateNav();
        return this.views.lab.render().open();
      };

      Router.prototype.loadLab = function(id) {
        var lab;
        this.clearViews('topBar');
        lab = new App.Lab.Views.Main({
          model: this.data.labs.get(id)
        });
        return lab.render().open();
      };

      return Router;

    })(Backbone.Router);
    return _ref = [Model, Router], exports.Model = _ref[0], exports.Router = _ref[1], _ref;
  });

  $(function() {
    return window.app = new App.Model;
  });

}).call(this);
